from suncraft_parsing import list_groups_as_string

all_list = [
    'Toilet Accessories', 
    'Kitchen & Accessories', 
    'Tub Accessories', 
    'Various Items', 
    'Glass Vessels', 
    'Tub Spout', 
    'Glass Vessel Accessories', 
    'Bathroom Sink Accessories', 
    'Tools', 
    'Special', 
    'Shower Heads', 
    'Bathroom Sink Drains', 
    'Shower Accessories', 
    'Tub Drains', 
    'Overflow Faceplate', 
    'Grid Drain', 
    'Various Items', 
    'Kit', #Subcats start here
    'Hose', 
    'Facet Pull Out Sprayer', 
    'Push & Lock', 
    'Rinse Spray', 
    'Aerator', 
    'Shower Arm', 
    'Escutcheon', 
    'One Piece', 
    'Vessel Mount', 
    'Mount', 
    'Facet Washer', 
    'Faucet', 
    'Clicker Style', 
    'Tailpiece', 
    'Strainer Assembly', 
    'Parts', 
    'Lever', 
    'Filler', 
    'Washer', 
    'Diverter', 
    'Facet Washer Bibb Chest', 
    'Shower Supply Elbow', 
    'Flange', 
    'Wrench', 
    'Rain', 
    'Pop Up', 
    'Drop In', 
    'Vacuum breaker', 
    'Adjustable Spray', 
    'Flow Control', 
    'Pipe Cutter', 
    'Single Function', 
    'Lift and Turn', 
    'Hose Connection', 
    'Hand Held', 
    'Drinking faucet', 
    '2.5 GPM', #tags start here
    'No Diverter', 
    'Massage', 
    '1.75"D', 
    '1/2" IPS', 
    'Three Piece', 
    'Cartridge Puller', 
    'Two Piece', 
    '2 Holes', 
    'Telescoping Adjustable Feature', 
    'U Shape', 
    'Square', 
    '59-80" hose', 
    'Stainless Steel', 
    'Slip Fit 5/8" OD', 
    'Spin and Seal', 
    'Copper Pipe', 
    'Rear Mount', 
    'Water Saving', 
    'Flush Mount', 
    'S Shape', 
    'nose mount', 
    'Bracket', 
    'Tapered', 
    'Grid Drain', 
    'Kit', 
    '1 1/2" (Coarse Thread)', 
    'Duplex', 
    'Adjustable', 
    'Jr Duo', 
    'Pop Up Assembly', 
    'Sillcock Key', 
    'Button', 
    'Parts', 
    '1.75 GPM', 
    'Clicker Stopper', 
    '1.5 GPM', 
    '2.2 GPM', 
    'Step', 
    'Spray Head', 
    '8"', 
    'Nut Wrench', 
    'Nipple Extractor', 
    '3/4" IPS', 
    '2.0 GPM', 
    'Economy', 
    'PVC', 
    'Clog Resistant', 
    'Hose Guide', 
    '1.2 GPM', 
    'Industrial', 
    'Hose Connection', 
    'Half & Half', 
    'No Overflow', 
    'Plastic', 
    'Stopper', 
    '7"D', 
    'Deep Cup', 
    'Hook', 
    'Zinc', 
    '1 1/4" (Fine Thread)', 
    'Wide', 
    'Socket Wrench', 
    'Convert', 
    'Plug Wrench', 
    'Dome', 
    'Basket', 
    'Pop Up', 
    'Adjustable Spray', 
    'De-burring Tool', 
    'Jet', 
    'Carded', 
    'Jewel Series', 
    'pliers', 
    'Front Diverter', 
    'Hose', 
    '®Mixet Style 4', 
    'Round', 
    'Arm Mount', 
    '1 hole', 
    'Flat', 
    'All Brass', 
    'Straight', 
    'Strap Wrench', 
    'Escutchon', 
    '1-4-All Universal Fit', 
    'Beveled', 
    'Free Rotateing Connector Nut', 
    'Jaws', 
    '4.5"D', 
    'Spud Chuck', 
    'L Shape', 
    'Swivel Connector', 
    'Flow Control', 
    '10 Sizes', 
    'Faucet Seat', 
    'Single Function', 
    '1.8 GPM', 
    'Basin Wrench', 
    '6"D', 
    'Strainer Wrench', 
    'Rear Diverter', 
    'With Overflow', 
    'Wall Mount', 
    '5 Function']


filepath = "downloaded_json_dbs/"
suncraft_database_file = "SClist_2023_08_22_08:20AM.json"


looking_for = all_list # Spelling and case sensitive at least at the moment, must be a list

type_of_group = "Categories" # Abrevations accepted "cat, sub, tag"





